default: &default
  adapter: postgresql
  username:
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hartl-app_development

test:
  <<: *default
  database: hartl-app_test

production:
  <<: *default
  database: hartl-app_production

